name: Build application

on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: >-
    ${{ github.ref != 'refs/heads/master' &&
        github.event_name != 'merge_group' &&
        !startsWith(github.ref, 'refs/heads/gh-readonly-queue') }}

permissions:
  contents: read
  issues: write
  pull-requests: write
  packages: read
  pages: write
  id-token: write

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml

  ubuntu:
    needs:
      - pre-commit
    if: ${{ needs.pre-commit.outputs.md_only != 'true' }}
    uses: ./.github/workflows/ubuntu.yml
    with:
      is_nightly: ${{ github.event_name == 'schedule' }}

  mac:
    needs:
      - pre-commit
    if: ${{ needs.pre-commit.outputs.md_only != 'true' }}
    uses: ./.github/workflows/mac.yml

  windows:
    needs:
      - pre-commit
    if: ${{ needs.pre-commit.outputs.md_only != 'true' }}
    uses: ./.github/workflows/windows.yml

  perf:
    needs:
      - pre-commit
      - ubuntu
      - mac
      - windows
    if: ${{ needs.pre-commit.outputs.md_only != 'true' }}
    uses: ./.github/workflows/perf.yml

  pages:
    needs:
      - pre-commit
      - perf
    if: ${{ needs.pre-commit.outputs.md_only != 'true' }}
    uses: ./.github/workflows/pages.yml
